In [2]:
import numpy as np

In [3]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6, 7, 8, 9, 10])

In [4]:
arr1-arr2  # Element-wise subtraction

array([-5, -5, -5, -5, -5])

In [5]:
arr1*arr2  # Element-wise multiplication (vector multiplication)

array([ 6, 14, 24, 36, 50])

In [6]:
arr1*2 #scalar multiplication

array([ 2,  4,  6,  8, 10])

In [7]:
arr2>3

array([ True,  True,  True,  True,  True])

In [8]:
arr1>3

array([False, False, False,  True,  True])

In [9]:
arr3=np.arange(6).reshape(2, 3)  # Create a 2D array with shape (2, 3)
arr4=np.arange(6, 12).reshape(3, 2)  # Create another 2D array with shape (2, 3)

In [10]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [14]:
arr1.dot(arr2)

np.int64(130)

In [15]:
arr1.dot(arr3)

ValueError: shapes (5,) and (2,3) not aligned: 5 (dim 0) != 2 (dim 0)

In [16]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [17]:
arr4.min()

np.int64(6)

In [18]:
arr4.max()

np.int64(11)

In [19]:
arr4.min(axis=0)

array([6, 7])

In [20]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [21]:
arr4.sum()

np.int64(51)

In [22]:
arr4.sum(axis=0)

array([24, 27])

In [23]:
arr4.mean()

np.float64(8.5)

In [24]:
arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [25]:
arr4.std() # Standard deviation

np.float64(1.707825127659933)

In [26]:
arr4.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [27]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [28]:
np.median(arr4)  # Median of the entire array

np.float64(8.5)

In [29]:
np.exp(arr4)  # Element-wise exponential

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

## Reshaping Numpy Array

In [30]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
arr4.ndim

2

In [32]:
arr4.ravel() # Flatten the array

array([ 6,  7,  8,  9, 10, 11])

In [33]:
arr4.reshape(2, 3)  # Reshape to (2, 3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
arr4.transpose()  # Transpose the array

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [35]:
arr5= arr4.transpose()  # Transpose the array

In [36]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
arr5=np.arange(12,18).reshape(2, 3)

In [38]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [39]:
np.vstack((arr5, arr3))  # Vertical stack of arr5 and arr3

array([[12, 13, 14],
       [15, 16, 17],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [40]:
np.hstack((arr5, arr3))

array([[12, 13, 14,  0,  1,  2],
       [15, 16, 17,  3,  4,  5]])