#Learn About Numpy

In [1]:
import numpy as np

#Creating Array From List

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
type(arr_1d)  # Check the type of the 1D array
type(arr_2d)  # Check the type of the 2D array

numpy.ndarray

In [4]:
arr3=np.zeros((2, 3))  # Create a 2D array of zeros
print("2D Array of Zeros:\n", arr3)

2D Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr5=np.identity(3)  # Create a 3x3 identity matrix
print("Identity Matrix:\n", arr5)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
arr6=np.arange(10)
print("Array with arange:\n", arr6)

Array with arange:
 [0 1 2 3 4 5 6 7 8 9]


In [7]:
arr7=np.linspace(1, 10, 10)  # Create an array with 5 evenly spaced values between 0 and 1
print("Array with linspace:\n", arr7)

Array with linspace:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
arr8=arr7.copy()
print("Copied Array:\n", arr8)

Copied Array:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [9]:
arr_1d.shape

(5,)

In [10]:
arr3.shape

(2, 3)

In [11]:
arr9=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Create a 3D array
print("3D Array:\n", arr9)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
arr9.shape

(2, 2, 2)

In [13]:
arr9.ndim  # Check the number of dimensions of the 3D array

3

In [14]:
arr_2d.ndim 

2

In [15]:
arr9.size

8

In [16]:
arr9.itemsize

8

In [17]:
arr8.itemsize

8

In [18]:
arr9.dtype  # Check the data type of the elements in the 3D array

dtype('int64')

In [19]:
arr7.dtype  # Check the data type of the elements in the 1D array created with linspace

dtype('float64')

In [20]:
arr9.astype

<function ndarray.astype>

In [21]:
arr9.astype('float')  # Convert the 3D array to float type

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [22]:
arr9.astype('int')  # Convert the 3D array to int type

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#List Vs Numpy Array

In [23]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2

print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.1984405517578125

 Numpy operation time:  0.01140904426574707


In [24]:
lista = range(100)
arr11=np.arange(100)

In [25]:
import sys

In [26]:
print (sys.getsizeof(87)*len(lista))

2800


In [27]:
print(arr11.itemsize*arr11.size)

800


In [28]:
import time

In [29]:
x=range(1000000)
y=range(1000000, 2000000)

start_time = time.time()

c=[(x,y) for x,y in zip(x,y)]
print("Time taken for list comprehension: ", time.time() - start_time)

c=[x+y for x,y in zip(x,y)]
print("Time taken for list comprehension with addition: ", 
      time.time() - start_time)

Time taken for list comprehension:  0.48040151596069336
Time taken for list comprehension with addition:  0.8847582340240479


In [30]:
a = np.arange(100000000)
b = np.arange(100000000, 200000000)

start_time = time.time()

c = a + b
print("Time taken for numpy array addition: ", 
      time.time() - start_time)

Time taken for numpy array addition:  8.223222255706787


## Indexing Slicing And Iteration

## ✅ 1. Indexing

In [31]:
import numpy as np
a = np.array([10, 20, 30, 40])
print(a[0])     # 10
print(a[-1])    # 40

10
40


In [32]:
b = np.array([[1, 2], [3, 4]])
print(b[0, 1])  # 2
print(b[1][0])  # 3

2
3


In [33]:
arr12 = np.arange(24).reshape(6, 4)
arr12 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## ✅ 2. Slicing
Extract a subarray using start:stop:step.

👉 1D Slicing

In [34]:
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])      # [20 30 40]
print(a[:3])       # [10 20 30]
print(a[::2])      # [10 30 50]

[20 30 40]
[10 20 30]
[10 30 50]


In [35]:
b = np.array([[1, 2, 3],
            [4, 5, 6], 
            [7, 8, 9]])
print(b[0:2, 1:])  # [[2 3] [5 6]]


[[2 3]
 [5 6]]


In [36]:
arr12[:,2:4]
arr12[:,1:3]  # Slicing to get specific columns


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [37]:
arr12[2:4, 1:3]  # Slicing to get specific rows and columns

array([[ 9, 10],
       [13, 14]])

In [38]:
arr12[4:, 2:]  # Slicing to get specific rows and columns

array([[18, 19],
       [22, 23]])

✅ 3. Iteration
👉 Iterate Over 1D Array

In [39]:
#👉 Iterate Over 1D Array
a = np.array([1, 2, 3])
for i in a:
    print(i)

1
2
3


In [40]:
#👉 Iterate Over 2D Array
b = np.array([[1, 2], [3, 4]])
for row in b:
    for val in row:
        print(val)


1
2
3
4


In [41]:
for i in arr12:
    print(i)  # Print each row of the array

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [42]:
for i in np.nditer(arr12):
    print(i)  # Print each element of the array using nditer    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
