#Learn About Numpy

In [1]:
import numpy as np

#Creating Array From List

In [10]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [15]:
type(arr_1d)  # Check the type of the 1D array
type(arr_2d)  # Check the type of the 2D array

numpy.ndarray

In [16]:
arr3=np.zeros((2, 3))  # Create a 2D array of zeros
print("2D Array of Zeros:\n", arr3)

2D Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
arr5=np.identity(3)  # Create a 3x3 identity matrix
print("Identity Matrix:\n", arr5)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr6=np.arange(10)
print("Array with arange:\n", arr6)

Array with arange:
 [0 1 2 3 4 5 6 7 8 9]


#List Vs Numpy Array

In [11]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.1282641887664795

 Numpy operation time:  0.004999876022338867
